version: '3.6'
services:
    wa-discovery-service:
        container_name: wa-discovery
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8273:8273"
        networks:
            bridge_network:
                aliases:
                    - discovery.wa
        environment:
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery.wa:8273/eureka
        restart: always

networks:
    bridge_network:
        driver: bridge