server:
    port: ${PORT:8273}

spring:
    application:
        name: weekly-achievements-discovery-service

eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/